spring:
  application:
    name: shoppy

  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/shoppy
    username: demo
    password: demo

  jpa:
    hibernate:
      ddl-auto: create

  security:
    user:
      name: demo
      password: demo

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

logging:
  level:
    root: warn
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /api-docs
