spring:
  application:
    name: shoppy

  main:
    banner-mode: off

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900
    refresh-token-expiration: 604800

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

app:
  payment:
    url:
      success-path: /api/checkout/success
      cancel-path: /api/checkout/cancel

    stripe:
      secret-key: ${STRIPE_SECRET_KEY}
      webhook-secret-key: ${STRIPE_WEBHOOK_SECRET_KEY}
